export const langList = [
  { name: "English", code: "en" },
  { name: "French", code: "fr" },
  { name: "Italian", code: "it" },
  { name: "Chinese", code: "zh" },
  { name: "German", code: "de" },
  { name: "Spanish", code: "es" },
  { name: "Hindi", code: "hi" },
  { name: "Arabic", code: "ar" },
  { name: "Portuguese", code: "pt" },
  { name: "Bengali", code: "bn" },
  { name: "Russian", code: "ru" },
  { name: "Japanese", code: "ja" },
  { name: "Korean", code: "ko" },
  { name: "Vietnamese", code: "vi" },
  { name: "Turkish", code: "tr" },
  { name: "Polish", code: "pl" },
  { name: "Dutch", code: "nl" },
  { name: "Hungarian", code: "hu" },
  { name: "Czech", code: "cs" },
  { name: "Danish", code: "da" },
  { name: "Norwegian Bokmål", code: "nb" },
  { name: "Ukrainian", code: "uk" },
  { name: "Romanian", code: "ro" },
  { name: "Bulgarian", code: "bg" },
  { name: "Catalan", code: "ca" },
  { name: "Irish", code: "ga" },
  { name: "Tagalog", code: "tl" },
  { name: "Thai", code: "th" },
  { name: "Hebrew", code: "il" },
];
